import 'song.dart';

class Playlist {
  final String id;
  final String name;
  final String? description;
  final String? coverUrl;
  final List<Song> songs;
  final DateTime createdAt;
  final bool isAutoGenerated;

  const Playlist({
    required this.id, required this.name, this.description,
    this.coverUrl, this.songs = const [], required this.createdAt,
    this.isAutoGenerated = false,
  });

  Playlist copyWith({
    String? id, String? name, String? description, String? coverUrl,
    List<Song>? songs, DateTime? createdAt, bool? isAutoGenerated,
  }) {
    return Playlist(
      id: id ?? this.id, name: name ?? this.name,
      description: description ?? this.description,
      coverUrl: coverUrl ?? this.coverUrl, songs: songs ?? this.songs,
      createdAt: createdAt ?? this.createdAt,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id, 'name': name, 'description': description, 'coverUrl': coverUrl,
      'songs': songs.map((s) => s.toJson()).toList(),
      'createdAt': createdAt.toIso8601String(),
      'isAutoGenerated': isAutoGenerated,
    };
  }

  factory Playlist.fromJson(Map<String, dynamic> json) {
    return Playlist(
      id: json['id'] as String, name: json['name'] as String,
      description: json['description'] as String?,
      coverUrl: json['coverUrl'] as String?,
      songs: (json['songs'] as List?)
              ?.map((s) => Song.fromJson(s as Map<String, dynamic>))
              .toList() ?? [],
      createdAt: DateTime.parse(json['createdAt'] as String),
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
    );
  }
}
